import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

import {
  ClerkProvider
} from '@clerk/nextjs'
import { AlertDialogProvider } from "@/features/alert-dialog/context/alert-dialog-context";
import { ImageGalleryProvider } from "@/features/image-storage/context/image-gallery-context";
import { BlogGalleryProvider } from "@/features/blog/context/blog-gallery-context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Environment Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <AlertDialogProvider>
        <ImageGalleryProvider>
          <BlogGalleryProvider>
            <html lang="vi">
              <body
                className={inter.className}
                suppressHydrationWarning
              >
                {children}
              </body>
            </html>
          </BlogGalleryProvider>
        </ImageGalleryProvider>
      </AlertDialogProvider>
    </ClerkProvider>
  );
}
