import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

import {
  ClerkProvider
} from '@clerk/nextjs'

import { AlertDialogProvider } from "@/features/alert-dialog/context/alert-dialog-context";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Environment Management System",
  description: "Generated by create next app",
  other: {
    'google-site-verification': 'googlefe9181b003380b71.html',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
          <html lang="vi">
            <body
              className={inter.className}
              suppressHydrationWarning
              >
              <AlertDialogProvider>
                {children}
              </AlertDialogProvider>
            </body>
          </html>
    </ClerkProvider>
  );
}
